apiVersion: v2
name: one-repo-multiple-paths-env2-product11-app18
description: Helm chart for one-repo-multiple-paths-env2-product11-app18
type: application
version: 0.1.302
appVersion: 1.14.2
maintainers:
  - name: GitOps Team
keywords:
  - application
  - microservice
annotations:
  environment: "env2"
  product: "product11"
  application: "app18"
metadata:
  labels:
    app: one-repo-multiple-paths-env2-product11-app18
