apiVersion: v2
name: one-repo-multiple-paths-env2-product11-app11
description: Helm chart for one-repo-multiple-paths-env2-product11-app11
type: application
version: 0.1.296
appVersion: 1.27.5
maintainers:
  - name: GitOps Team
keywords:
  - application
  - microservice
annotations:
  environment: "env2"
  product: "product11"
  application: "app11"
metadata:
  labels:
    app: one-repo-multiple-paths-env2-product11-app11
