apiVersion: v1
kind: Service
metadata:
  name: one-repo-multiple-paths-env6-product11-app3
  labels:
    app: one-repo-multiple-paths-env6-product11-app3
spec:
  selector:
    app: one-repo-multiple-paths-env6-product11-app3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
