apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-repo-multiple-paths-env2-product11-app26
  labels:
    app: one-repo-multiple-paths-env2-product11-app26
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-repo-multiple-paths-env2-product11-app26
  template:
    metadata:
      labels:
        app: one-repo-multiple-paths-env2-product11-app26
    spec:
      containers:
        - name: one-repo-multiple-paths
          image: nginx:1.27.5
          ports:
            - containerPort: 80
