apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-repo-multiple-paths-env2-product11-app7
  labels:
    app: one-repo-multiple-paths-env2-product11-app7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-repo-multiple-paths-env2-product11-app7
  template:
    metadata:
      labels:
        app: one-repo-multiple-paths-env2-product11-app7
    spec:
      containers:
        - name: one-repo-multiple-paths
          image: nginx:1.25.5
          ports:
            - containerPort: 80
