apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-repo-multiple-paths-env2-product11-app23
  labels:
    app: one-repo-multiple-paths-env2-product11-app23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-repo-multiple-paths-env2-product11-app23
  template:
    metadata:
      labels:
        app: one-repo-multiple-paths-env2-product11-app23
    spec:
      containers:
        - name: one-repo-multiple-paths
          image: nginx:1.26.3
          ports:
            - containerPort: 80
