apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-repo-multiple-paths-env2-product11-app27
  labels:
    app: one-repo-multiple-paths-env2-product11-app27
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-repo-multiple-paths-env2-product11-app27
  template:
    metadata:
      labels:
        app: one-repo-multiple-paths-env2-product11-app27
    spec:
      containers:
        - name: one-repo-multiple-paths
          image: nginx:1.23.4
          ports:
            - containerPort: 80
