apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-repo-multiple-paths-env2-product11-app25
  labels:
    app: one-repo-multiple-paths-env2-product11-app25
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-repo-multiple-paths-env2-product11-app25
  template:
    metadata:
      labels:
        app: one-repo-multiple-paths-env2-product11-app25
    spec:
      containers:
        - name: one-repo-multiple-paths
          image: nginx:1.14.2
          ports:
            - containerPort: 80
