apiVersion: v2
name: one-repo-multiple-paths-env2-product11-app1
description: Helm chart for one-repo-multiple-paths-env2-product11-app1
type: application
version: 0.1.308
appVersion: 1.14.0
maintainers:
  - name: GitOps Team
keywords:
  - application
  - microservice
annotations:
  environment: "env2"
  product: "product11"
  application: "app1"
metadata:
  labels:
    app: one-repo-multiple-paths-env2-product11-app1
