apiVersion: v2
name: one-repo-multiple-paths-env2-product11-app5
description: Helm chart for one-repo-multiple-paths-env2-product11-app5
type: application
version: 0.1.298
appVersion: 1.25.5
maintainers:
  - name: GitOps Team
keywords:
  - application
  - microservice
annotations:
  environment: "env2"
  product: "product11"
  application: "app5"
metadata:
  labels:
    app: one-repo-multiple-paths-env2-product11-app5
