apiVersion: v2
name: one-repo-multiple-paths-env2-product11-app3
description: Helm chart for one-repo-multiple-paths-env2-product11-app3
type: application
version: 0.1.335
appVersion: 1.23.4
maintainers:
  - name: GitOps Team
keywords:
  - application
  - microservice
annotations:
  environment: "env2"
  product: "product11"
  application: "app3"
metadata:
  labels:
    app: one-repo-multiple-paths-env2-product11-app3
