apiVersion: v1
kind: Service
metadata:
  name: one-repo-multiple-paths-env2-product11-app9
  labels:
    app: one-repo-multiple-paths-env2-product11-app9
spec:
  selector:
    app: one-repo-multiple-paths-env2-product11-app9
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
