apiVersion: v2
name: one-repo-multiple-paths-env2-product11-app17
description: Helm chart for one-repo-multiple-paths-env2-product11-app17
type: application
version: 0.1.229
appVersion: 1.24.0
maintainers:
  - name: GitOps Team
keywords:
  - application
  - microservice
annotations:
  environment: "env2"
  product: "product11"
  application: "app17"
metadata:
  labels:
    app: one-repo-multiple-paths-env2-product11-app17
